version: '2'
networks:
    robercan1979:
      driver: bridge
services:
    mysql:
        image: 'mariadb:10.4-bionic'
        user: root
        volumes:
            - '/var/lib/docker/volumes/mariadb_data/_data:/bitnami'
        networks:
            - robercan1979
        environment:
            - MYSQL_ROOT_PASSWORD=AF2016seg*
    web:
        build: .
        ports:
            - "4000:3000"
        networks:
            - robercan1979